---
title: "p8105_hw6"
author: Jiaqi Li and Leiyu Yue
---

In Problems 1 and 2, I worked with Leiyu Yue (UNI: ly2428).\
In this homework, we use “NYC restaurant” dataset.

### Problem 1

The GitHub repo containing our solution to this problem is [here](https://github.com/ljq312/p8105_hw6_jl5025_problem1).\
According to the requirement, we plot three different graphics for this problem.\
**The 10 most frequently used words in “Violation description” chart:**There is a violation description for each restaurant, and we are kind of curious about what words people use the most frequently to describe these restaurants. We “unnest-token”  the description, “anti-join” the data with “stopwords” and then count the frequency of each word. To make the bar graphic neat, we choose the top 10 used words. As you can see from the bar graphics,  people use “food”, “flies”, “properly”, “contact”, “surface”,  “improperly”, “equipment”, “maintained”, “vermin” and “constructed” very often to describe the restaurant in NYC and you can check the specific appearing times when you put your mouse on the bar. It is very funny to get “flies” in the result and it seems that people are not satisfied about the restaurant in NYC. \
**The percentage of “A”,“B”,“C” restaurants in NYC chart: **There is a grade for each restaurant in the dataset, so we calculated the percentage of restaurant numbers with every grade given the all restaurant numbers in NYC and made the plot a donut chart. It turns out that A takes up 81.8%, B takes up 14.6% and C takes up 3.65%. Overall, New Yorkers give most of the restaurants “A”.\
**The number of “A”/“B”/“C” restaurants for each boro chart:**As we live in Manhattan, we want to know in the restaurant numbers for each grade and we went deeper than that, making a bar chart showing the specific numbers of restaurant with different grade in each district of NYC(Manhattan, Bronx, Brooklyn, Queens, State Island). From the bar chart, for example, we can get the information that there are 61.608k “A” restaurants, 10.532k “B” restaurants and 2689 “C” restaurants in Manhattan.


### Problem 2

The GitHub repo containing the solution to this problem is [here](https://github.com/ljq312/p8105_hw6_jl5025_problem2).\
To increase the interaction, we add shiny to the three charts. We set two distinct sidebar widgets. One is “selectInput”, distinguished by “Cuisine description”, naming it as “Select cuisine type”. Another one is “radiobuttons”, distinguished by “boro”, naming it as “Select boro”.\
For the “**Select cuisine type**” widget,  we can filter “The 10 most frequently used words in ‘Violation description’ chart” and “The number of “A”/“B”/“C” restaurants for each boro chart” by choosing the cuisine type.\
For the “**Select boro**” widget, we can filter “The 10 most frequently used words in ‘Violation description’ chart” and “The percentage of “A”,“B”,“C” restaurants in NYC chart” by choosing boro(Manhattan, Bronx, Brooklyn, Queens, Staten Island).

