---
title: "NYC restaurant dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(readr)
library(dplyr)
library(tidytext)
library(shiny)
```

```{r}
### load data
nyc_inspections <- read_csv("./data/DOHMH_New_York_City_Restaurant_Inspection_Results.csv.gz", 
                           col_types = cols(building = col_character()),
                           na = c("NA", "N/A")) %>% 
  filter(grade %in% c("A", "B", "C"),
         boro != "Missing") %>% 
  mutate(boro = str_to_title(boro),
         inspection_num = row_number()) %>%
  select(inspection_num, boro, grade, cuisine_description, violation_description)
```

Column {data-width=650}
-----------------------------------------------------------------------

### The 10 most frequently used words in "violation description"

```{r}
inspection_words = nyc_inspections %>% 
  unnest_tokens(word, violation_description)

data(stop_words)

inspection_words = 
  anti_join(inspection_words, stop_words)

inspection_words %>% 
  count(word, sort = TRUE) %>% 
  head(10) %>% 
  mutate(word = fct_reorder(word, n)) %>% 
  plot_ly(x = ~word, y = ~n, type = "bar", color = ~word)
```

Column {data-width=350}
-----------------------------------------------------------------------

### The percentage of grade A, B, C restaurants in NYC

```{r}
nyc_inspections %>%
  group_by(grade) %>%
  summarize(count = n()) %>%
  mutate(percentage = paste(round(count/sum(count), 2)*100, "%")) %>% 
  plot_ly(labels = ~grade, values = ~count) %>%
  add_pie(hole = 0.6) %>%
  layout(showlegend = T,
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
```

### Number of grade A, B, C restaurants for each boro

```{r}
nyc_inspections %>% 
  group_by(boro, grade) %>% 
  summarize(n = n()) %>% 
  spread(key = grade, value = n) %>% 
  plot_ly( x = ~boro, y = ~A, type = 'bar', name = 'A') %>% 
  add_trace(y = ~B, name = "B") %>%
  add_trace(y = ~C, name = "C") %>% 
  layout(yaxis = list(title = 'Count'), barmode = 'stack')
```

